/**
 * Created by Administrator on 2017/4/26.
 */
export const RECORD_USERINFO='RECORD_USERINFO'
export const GET_USERINFO='GET_USERINFO'
export const UPDATE_AUTHFLAG='UPDATE_AUTHFLAG'
export const RECORD_USERDETAILINFO='RECORD_USERDETAILINFO'
